```{r echo=FALSE, warning=FALSE}
#Change this line to match the created temporary directory
dir = file.path(dir.existing, "temp")

date=readRDS(file.path(dir,"date.rds"))
plate=readRDS(file.path(dir,"split.rds"))
file.setup=readRDS(file.path(dir,"file-setup.rds"))
```

SETUP Report: `r date` - `r plate`
========================================================
File name: `r file.setup`


Strains:
```{r echo=FALSE, warning=FALSE}
options(width = 110)
strains=readRDS(file.path(dir,"strains.rds"))
strains
```

Contaminated wells:
```{r echo=FALSE, warning=FALSE}
contam=readRDS(file.path(dir,"contam.rds"))
contam
```


Number of L4s sorted:
```{r echo=FALSE,fig.width=15,fig.height=10, warning=FALSE}
plot.setup.sorted=readRDS(file.path(dir,"plot-setup-sorted.rds"))
plot.setup.sorted
```



Population size (factored color):
```{r echo=FALSE,fig.width=15,fig.height=10, warning=FALSE}
plot.setup.pop=readRDS(file.path(dir,"plot-setup-pop.rds"))
plot.setup.pop
```


- Top left: TOF mean
- Bottom left: TOF median
- Top right: EXT mean
- Bottom right: EXT median
```{r echo=FALSE,fig.width=15,fig.height=10, warning=FALSE}
plot.setup.tofext=readRDS(file.path(dir,"plot-setup-tofext.rds"))
plot.setup.tofext
```


procSetup dataset:
```{r echo=FALSE, warning=FALSE}
setup.proc=readRDS(file.path(dir,"setup-proc.rds"))
setup.proc
```
