```{r echo=FALSE}
#Change this line to match the created temporary directory
dir = file.path(dir.existing, "temp")

date=readRDS(file.path(dir,"date.rds"))
plate=readRDS(file.path(dir,"split.rds"))
file.score=readRDS(file.path(dir,"file-score.rds"))
```

SCORE Report: `r date` - `r plate`
========================================================
File name: `r file.score`


Strain information:
```{r echo = FALSE}
options(width = 110)
strains=readRDS(file.path(dir,"strains.rds"))
strains
```


Contaminated wells:
```{r echo=FALSE}
contam=readRDS(file.path(dir,"contam.rds"))
contam
```


Possibly contaminated wells:
```{r echo=FALSE}
possibleContam = readRDS(file.path(dir,"possibleContam.rds"))
possibleContam
```


Number of worms in each well:
```{r echo=FALSE,fig.width=15,fig.height=10}
plot.score.pop=readRDS(file.path(dir,"plot-score-pop.rds"))
plot.score.pop
```



+ Top left: Mean TOF
+ Top right: Mean EXT
+ Bottom left: Median TOF
+ Bottom right: Median EXT
```{r echo=FALSE,fig.width=15,fig.height=10}
plot.score.tofext=readRDS(file.path(dir,"plot-score-tofext.rds"))
plot.score.tofext
```



Red fluorescence (normalized by mean TOF):
+ Top left: Mean red
+ Bottom right: Median red
```{r echo=FALSE,fig.width=15,fig.height=10}
plot.score.red=readRDS(file.path(dir,"plot-score-red.rds"))
plot.score.red
```



Life-stage distribution:
```{r echo=FALSE}
plot.score.dist=readRDS(file.path(dir,"plot-score-dist.rds"))
plot.score.dist
```



Processed dataset:
```{r echo=FALSE}
proc=readRDS(file.path(dir,"proc.rds"))
proc
```


