```{r echo=FALSE}
date=readRDS("~/date.rds")
plate=readRDS("~/split.rds")
file.score=readRDS("~/file-score.rds")
```

SCORE Report: `r date` - `r plate`
========================================================
File name: `r file.score`


Strain information:
```{r}
options(width = 110)
strains=readRDS("~/strains.rds")
strains
```


Contaminated wells:
```{r echo=FALSE}
contam=readRDS("~/contam.rds")
contam
```


Number of worms in each well:
```{r echo=FALSE,fig.width=15,fig.height=10}
plot.score.pop=readRDS("~/plot-score-pop.rds")
plot.score.pop
```



+ Top left: Mean TOF
+ Top right: Mean EXT
+ Bottom left: Median TOF
+ Bottom right: Median EXT
```{r echo=FALSE,fig.width=15,fig.height=10}
plot.score.tofext=readRDS("~/plot-score-tofext.rds")
plot.score.tofext
```



Red fluorescence (normalized by mean TOF):
+ Top left: Mean red
+ Bottom right: Median red
```{r echo=FALSE,fig.width=15,fig.height=10}
plot.score.red=readRDS("~/plot-score-red.rds")
plot.score.red
```



Life-stage distribution:
```{r echo=FALSE}
plot.score.dist=readRDS("~/plot-score-dist.rds")
plot.score.dist
```



Processed dataset:
```{r echo=FALSE}
proc=readRDS("~/proc.rds")
proc
```


